jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.url=jdbc:postgresql://database:5432/liferay_crm_db
jdbc.default.username=liferay
jdbc.default.password=liferaypassword
setup.wizard.enabled=false
